upstream: https://github.com/community-scripts/ProxmoxVE
modsdir: codemods
stage: true
commit: true
push: true
codemods:
- description: Modify Build Func
  mod: sed
  match: ct/*.sh
  args:
  - https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/misc/build.func
  - https://raw.githubusercontent.com/bketelsen/IncusScripts/main/misc/build.func
- description: Modify Build Func Refs
  mod: sed
  match: ct/*.sh
  args:
  - https://raw.githubusercontent.com/community-scripts/ProxmoxVE/refs/heads/main/misc/build.func
  - https://raw.githubusercontent.com/bketelsen/IncusScripts/refs/heads/main/misc/build.func
- description: Whiptail ct
  mod: sed
  match: ct/*.sh
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail install
  mod: sed
  match: install/*.sh
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail misc sh
  mod: sed
  match: misc/*.sh
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail misc func
  mod: sed
  match: misc/*.func
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail func LXC
  mod: sed
  match: misc/*.func
  args:
  - LXC Container
  - Incus Container
- description: Source Install
  mod: sed
  match: install/*.sh
  args:
  - source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"
  - source /install.func
- description: Whiptail func Updater
  mod: sed
  match: misc/*.func
  args:
  - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/${app}.sh
  - https://github.com/bketelsen/IncusScripts/raw/main/ct/${app}.sh
- description: Header Updates
  mod: sed
  match: misc/*.func
  args:
  - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/headers/
  - https://github.com/bketelsen/IncusScripts/raw/main/ct/headers/
- description: PVE Check Function
  mod: bashfunc
  match: misc/build.func
  args:
  - pve_check
  - codemods/pve_check.sh
- description: PVE Description
  mod: bashfunc
  match: misc/build.func
  args:
  - description
  - codemods/description.sh
- description: PVE Start Function
  mod: bashfunc
  match: misc/build.func
  args:
  - start
  - codemods/start.sh
- description: PVE Storage Function
  mod: bashfunc
  match: misc/build.func
  args:
  - check_container_storage
  - codemods/check_container_storage.sh
- description: PVE Build Function
  mod: bashfunc
  match: misc/build.func
  args:
  - build_container
  - codemods/build_container.sh
- description: Replace create_lxc
  mod: replacefile
  match: ct/create_lxc.sh
  args:
  - codemods/create_lxc.sh
- description: Replace install
  mod: bashfunc
  match: misc/build.func
  args:
  - install_script
  - codemods/install_script.sh
