# JSON-Mapping aus der Migrationstabelle
$mapping = @(
    @{script="2fauth"; category_id=6},
    @{script="5etools"; category_id=24},
    @{script="actualbudget"; category_id=23},
    @{script="add-lxc-iptag"; category_id=1},
    @{script="add-netbird-lxc"; category_id=1},
    @{script="add-tailscale-lxc"; category_id=1},
    @{script="adguard"; category_id=5},
    @{script="adventurelog"; category_id=24},
    @{script="agentdvr"; category_id=15},
    @{script="all-templates"; category_id=1},
    @{script="alpine"; category_id=2},
    @{script="apache-cassandra"; category_id=8},
    @{script="apache-couchdb"; category_id=8},
    @{script="apache-guacamole"; category_id=21},
    @{script="apt-cacher-ng"; category_id=4},
    @{script="archivebox"; category_id=12},
    @{script="aria2"; category_id=11},
    @{script="audiobookshelf"; category_id=13},
    @{script="authentik"; category_id=6},
    @{script="autobrr"; category_id=19},
    @{script="bazarr"; category_id=14},
    @{script="blocky"; category_id=5},
    @{script="bookstack"; category_id=12},
    @{script="bunkerweb"; category_id=21},
    @{script="caddy"; category_id=21},
    @{script="calibre-web"; category_id=12},
    @{script="casaos"; category_id=2},
    @{script="changedetection"; category_id=9},
    @{script="channels"; category_id=13},
    @{script="checkmk"; category_id=9},
    @{script="clean-lxcs"; category_id=1},
    @{script="cloudflared"; category_id=4},
    @{script="cockpit"; category_id=10},
    @{script="code-server"; category_id=20},
    @{script="commafeed"; category_id=10},
    @{script="cron-update-lxcs"; category_id=1},
    @{script="cronicle"; category_id=19},
    @{script="crowdsec"; category_id=6},
    @{script="daemonsync"; category_id=19},
    @{script="dashy"; category_id=10},
    @{script="debian-vm"; category_id=1},
    @{script="debian"; category_id=2},
    @{script="deconz"; category_id=17},
    @{script="deluge"; category_id=11},
    @{script="docker"; category_id=3},
    @{script="dockge"; category_id=3},
    @{script="dotnetaspwebapi"; category_id=20},
    @{script="emby"; category_id=13},
    @{script="emqx"; category_id=18},
    @{script="ersatztv"; category_id=13},
    @{script="esphome"; category_id=16},
    @{script="evcc"; category_id=16},
    @{script="fenrus"; category_id=10},
    @{script="fhem"; category_id=16},
    @{script="filebrowser"; category_id=11},
    @{script="firefly"; category_id=23},
    @{script="flaresolverr"; category_id=4},
    @{script="flowiseai"; category_id=20},
    @{script="forgejo"; category_id=20},
    @{script="frigate"; category_id=15},
    @{script="fstrim"; category_id=2},
    @{script="ghost"; category_id=21},
    @{script="gitea"; category_id=20},
    @{script="glance"; category_id=9},
    @{script="glances"; category_id=9},
    @{script="glpi"; category_id=28},
    @{script="go2rtc"; category_id=16},
    @{script="gokapi"; category_id=11},
    @{script="gotify"; category_id=18},
    @{script="grafana"; category_id=9},
    @{script="grist"; category_id=12},
    @{script="grocy"; category_id=16},
    @{script="haos-vm"; category_id=1},
    @{script="headscale"; category_id=4},
    @{script="heimdall-dashboard"; category_id=10},
    @{script="hivemq"; category_id=18},
    @{script="hoarder"; category_id=12},
    @{script="homarr"; category_id=10},
    @{script="homeassistant-core"; category_id=16},
    @{script="homeassistant"; category_id=16},
    @{script="homebox"; category_id=25},
    @{script="homebridge"; category_id=16},
    @{script="homepage"; category_id=10},
    @{script="host-backup"; category_id=7},
    @{script="hyperhdr"; category_id=13},
    @{script="hyperion"; category_id=13},
    @{script="influxdb"; category_id=8},
    @{script="inspircd"; category_id=18},
    @{script="iobroker"; category_id=16},
    @{script="iventoy"; category_id=2},
    @{script="jackett"; category_id=14},
    @{script="jellyfin"; category_id=13},
    @{script="jellyseerr"; category_id=14},
    @{script="jenkins"; category_id=19},
    @{script="kavita"; category_id=13},
    @{script="kernel-clean"; category_id=2},
    @{script="kernel-pin"; category_id=2},
    @{script="keycloak"; category_id=6},
    @{script="kimai"; category_id=28},
    @{script="komga"; category_id=13},
    @{script="komodo"; category_id=20},
    @{script="kubo"; category_id=11},
    @{script="lazylibrarian"; category_id=14},
    @{script="lidarr"; category_id=14},
    @{script="linkwarden"; category_id=12},
    @{script="listmonk"; category_id=22},
    @{script="lldap"; category_id=6},
    @{script="lubelogger"; category_id=9},
    @{script="mafl"; category_id=25},
    @{script="magicmirror"; category_id=16},
    @{script="mariadb"; category_id=8},
    @{script="matterbridge"; category_id=22},
    @{script="mediamtx"; category_id=13},
    @{script="medusa"; category_id=14},
    @{script="memos"; category_id=12},
    @{script="meshcentral"; category_id=4},
    @{script="metadata"; category_id=13},
    @{script="metube"; category_id=13},
    @{script="microcode"; category_id=2},
    @{script="mikrotik-routeros"; category_id=4},
    @{script="mongodb"; category_id=8},
    @{script="monitor-all"; category_id=9},
    @{script="motioneye"; category_id=15},
    @{script="mqtt"; category_id=18},
    @{script="mylar3"; category_id=14},
    @{script="myspeed"; category_id=4},
    @{script="mysql"; category_id=8},
    @{script="n8n"; category_id=19},
    @{script="navidrome"; category_id=13},
    @{script="neo4j"; category_id=8},
    @{script="netbox"; category_id=4},
    @{script="netdata"; category_id=9},
    @{script="nextcloud-vm"; category_id=1},
    @{script="nextcloudpi"; category_id=2},
    @{script="nextpvr"; category_id=15},
    @{script="nginxproxymanager"; category_id=21},
    @{script="nocodb"; category_id=28},
    @{script="node-red"; category_id=19},
    @{script="notifiarr"; category_id=22},
    @{script="ntfy"; category_id=22},
    @{script="nzbget"; category_id=11},
    @{script="octoprint"; category_id=16},
    @{script="olivetin"; category_id=10},
    @{script="omada"; category_id=4},
    @{script="ombi"; category_id=14},
    @{script="omv"; category_id=2},
    @{script="onedev"; category_id=20},
    @{script="opengist"; category_id=20},
    @{script="openhab"; category_id=16},
    @{script="openobserve"; category_id=9},
    @{script="openwebui"; category_id=20},
    @{script="openwrt"; category_id=2},
    @{script="overseerr"; category_id=14},
    @{script="owncast"; category_id=13},
    @{script="owncloud-vm"; category_id=1},
    @{script="pairdrop"; category_id=11},
    @{script="paperless-ngx"; category_id=12},
    @{script="part-db"; category_id=28},
    @{script="pbs"; category_id=7},
    @{script="peanut"; category_id=4},
    @{script="petio"; category_id=14},
    @{script="pf2etools"; category_id=24},
    @{script="photoprism"; category_id=13},
    @{script="pialert"; category_id=6},
    @{script="pihole"; category_id=5},
    @{script="pimox-haos-vm"; category_id=1},
    @{script="pingvin"; category_id=25},
    @{script="plex"; category_id=13},
    @{script="pocketbase"; category_id=28},
    @{script="podman-homeassistant"; category_id=3},
    @{script="podman"; category_id=3},
    @{script="post-pbs-install"; category_id=7},
    @{script="post-pve-install"; category_id=1},
    @{script="postgresql"; category_id=8},
    @{script="prometheus-alertmanager"; category_id=9},
    @{script="prometheus"; category_id=9},
    @{script="prowlarr"; category_id=14},
    @{script="proxmox-datacenter-manager"; category_id=1},
    @{script="ps5-mqtt"; category_id=18},
    @{script="qbittorrent"; category_id=11},
    @{script="rabbitmq"; category_id=18},
    @{script="radarr"; category_id=14},
    @{script="rdtclient"; category_id=11},
    @{script="readarr"; category_id=14},
    @{script="readeck"; category_id=12},
    @{script="recyclarr"; category_id=14},
    @{script="redis"; category_id=8},
    @{script="rtsptoweb"; category_id=15},
    @{script="runtipi"; category_id=2},
    @{script="sabnzbd"; category_id=11},
    @{script="scaling-governor"; category_id=2},
    @{script="semaphore"; category_id=19},
    @{script="sftpgo"; category_id=11},
    @{script="shinobi"; category_id=15},
    @{script="silverbullet"; category_id=12},
    @{script="smokeping"; category_id=9},
    @{script="snipeit"; category_id=28},
    @{script="sonarr"; category_id=14},
    @{script="spoolman"; category_id=16},
    @{script="stirling-pdf"; category_id=12},
    @{script="syncthing"; category_id=11},
    @{script="tandoor"; category_id=12},
    @{script="tasmoadmin"; category_id=16},
    @{script="tautulli"; category_id=13},
    @{script="tdarr"; category_id=13},
    @{script="technitiumdns"; category_id=5},
    @{script="teddycloud"; category_id=13},
    @{script="the-lounge"; category_id=22},
    @{script="threadfin"; category_id=13},
    @{script="tianji"; category_id=25},
    @{script="traccar"; category_id=16},
    @{script="traefik"; category_id=21},
    @{script="transmission"; category_id=11},
    @{script="trilium"; category_id=12},
    @{script="turnkey"; category_id=2},
    @{script="typesense"; category_id=20},
    @{script="ubuntu"; category_id=2},
    @{script="ubuntu2204-vm"; category_id=1},
    @{script="ubuntu2404-vm"; category_id=1},
    @{script="umami"; category_id=9},
    @{script="unbound"; category_id=5},
    @{script="unifi"; category_id=4},
    @{script="unmanic"; category_id=13},
    @{script="update-lxcs"; category_id=1},
    @{script="update-repo"; category_id=25},
    @{script="uptimekuma"; category_id=9},
    @{script="vaultwarden"; category_id=6},
    @{script="vikunja"; category_id=12},
    @{script="wallos"; category_id=2},
    @{script="wastebin"; category_id=25},
    @{script="watchyourlan"; category_id=4},
    @{script="wavelog"; category_id=9},
    @{script="webmin"; category_id=2},
    @{script="whisparr"; category_id=14},
    @{script="whoogle"; category_id=25},
    @{script="wikijs"; category_id=12},
    @{script="wireguard"; category_id=4},
    @{script="wordpress"; category_id=21},
    @{script="yunohost"; category_id=2},
    @{script="zabbix"; category_id=9},
    @{script="zammad"; category_id=28},
    @{script="zigbee2mqtt"; category_id=17},
    @{script="zipline"; category_id=11},
    @{script="zoraxy"; category_id=4},
    @{script="zwave-js-ui"; category_id=17}
)

# Dateien im aktuellen Verzeichnis durchsuchen
# Dateien im aktuellen Verzeichnis durchsuchen
Get-ChildItem -Filter *.json | ForEach-Object {
    $filePath = $_.FullName
    $content = Get-Content -Path $filePath -Raw

    # Extrahieren des "slug"-Werts
    if ($content -match '"slug":\s*"(.*?)"') {
        $slug = $matches[1]
        if ($mapping.ContainsKey($slug)) {
            $newCategory = $mapping[$slug]

            # Ersetzen der Kategorie-Nummer
            $content = $content -replace '(?<=\s"categories":\s\[\s*)\d+(?=\s*\])', $newCategory

            # Geänderte Datei speichern
            Set-Content -Path $filePath -Value $content -Encoding UTF8
            Write-Host "Kategorie in Datei aktualisiert: $filePath"
        } else {
            Write-Host "Kein Mapping für $slug in Datei $filePath gefunden."
        }
    } else {
        Write-Host "Kein 'slug'-Eintrag in Datei $filePath gefunden."
    }
}

